In [3]:
import pandas as pd

df = pd.read_csv("class_ipl_22-26_dataset.csv")

In [4]:
df.head()

,date,season,city,venue,team1,team2,toss_winner,toss_decision,team1_runs,team1_wickets,...,win_by_wickets,player_of_match,match_referee,umpire1,umpire2,tv_umpire,reserve_umpire,overs_limit,team1_players,team2_players
0,26-03-2022,2022,Mumbai,"Wankhede Stadium, Mumbai",Chennai Super Kings,Kolkata Knight Riders,Kolkata Knight Riders,field,131,5,...,6,UT Yadav,M Nayyar,AK Chaudhary,Nitin Menon,VK Sharma,Chirra Ravikanthreddy,20,"RD Gaikwad, DP Conway, RV Uthappa, AT Rayudu, ...","AM Rahane, VR Iyer, N Rana, SS Iyer, SW Billin..."
1,27-03-2022,2022,Mumbai,"Brabourne Stadium, Mumbai",Mumbai Indians,Delhi Capitals,Delhi Capitals,field,177,5,...,4,Kuldeep Yadav,Prakash Bhatt,RJ Tucker,HAS Khalid,J Madanagopal,N Pandit,20,"RG Sharma, Ishan Kishan, Anmolpreet Singh, Til...","PP Shaw, TL Seifert, Mandeep Singh, RR Pant, L..."
2,27-03-2022,2022,Mumbai,"Dr DY Patil Sports Academy, Mumbai",Royal Challengers Bangalore,Punjab Kings,Punjab Kings,field,205,2,...,5,OF Smith,M Nayyar,Nitin Menon,YC Barde,AK Chaudhary,R Pandit,20,"F du Plessis, Anuj Rawat, V Kohli, KD Karthik,...","MA Agarwal, S Dhawan, PBB Rajapaksa, LS Living..."
3,28-03-2022,2022,Mumbai,"Wankhede Stadium, Mumbai",Lucknow Super Giants,Gujarat Titans,Gujarat Titans,field,158,6,...,5,Mohammed Shami,DS Manohar,PG Pathak,VK Sharma,RJ Tucker,GR Sadashiv Iyer,20,"KL Rahul, Q de Kock, E Lewis, MK Pandey, DJ Ho...","Shubman Gill, MS Wade, V Shankar, HH Pandya, D..."
4,29-03-2022,2022,Pune,"Maharashtra Cricket Association Stadium, Pune",Rajasthan Royals,Sunrisers Hyderabad,Sunrisers Hyderabad,field,210,6,...,0,SV Samson,Shakti Singh,BNJ Oxenford,UV Gandhe,KN Ananthapadmanabhan,MV Saidharshan Kumar,20,"JC Buttler, YBK Jaiswal, SV Samson, D Padikkal...","KS Williamson, Abhishek Sharma, RA Tripathi, N..."

In [6]:
df.shape

(367, 25)

In [7]:
df['team2'].unique()

array(['Kolkata Knight Riders', 'Delhi Capitals', 'Punjab Kings',
       'Gujarat Titans', 'Sunrisers Hyderabad',
       'Royal Challengers Bangalore', 'Lucknow Super Giants',
       'Mumbai Indians', 'Chennai Super Kings', 'Rajasthan Royals',
       'Royal Challengers Bengaluru'], dtype=object)

In [9]:
df[['team1', 'team2', 'toss_decision']]

                           team1                        team2 toss_decision
0            Chennai Super Kings        Kolkata Knight Riders         field
1                 Mumbai Indians               Delhi Capitals         field
2    Royal Challengers Bangalore                 Punjab Kings         field
3           Lucknow Super Giants               Gujarat Titans         field
4               Rajasthan Royals          Sunrisers Hyderabad         field
..                           ...                          ...           ...
362               Delhi Capitals        Kolkata Knight Riders         field
363  Royal Challengers Bengaluru               Gujarat Titans         field
364             Rajasthan Royals          Sunrisers Hyderabad         field
365             Rajasthan Royals               Gujarat Titans           bat
366               Gujarat Titans  Royal Challengers Bengaluru         field

[367 rows x 3 columns]

In [13]:
print(df['toss_decision'].unique())
print(df['team1'].nunique())
print(df['team2'].nunique())

['field' 'bat']
11
11

In [16]:
df_encoded = pd.get_dummies(df,columns=['team1', 'team2', 'toss_decision'], dtype=int)
pd.set_option('display.max_columns', None)
df_encoded.head()

,date,season,city,venue,toss_winner,team1_runs,team1_wickets,team2_runs,team2_wickets,winner,result_type,win_by_runs,win_by_wickets,player_of_match,match_referee,umpire1,umpire2,tv_umpire,reserve_umpire,overs_limit,team1_players,team2_players,team1_Chennai Super Kings,team1_Delhi Capitals,team1_Gujarat Titans,team1_Kolkata Knight Riders,team1_Lucknow Super Giants,team1_Mumbai Indians,team1_Punjab Kings,team1_Rajasthan Royals,team1_Royal Challengers Bangalore,team1_Royal Challengers Bengaluru,team1_Sunrisers Hyderabad,team2_Chennai Super Kings,team2_Delhi Capitals,team2_Gujarat Titans,team2_Kolkata Knight Riders,team2_Lucknow Super Giants,team2_Mumbai Indians,team2_Punjab Kings,team2_Rajasthan Royals,team2_Royal Challengers Bangalore,team2_Royal Challengers Bengaluru,team2_Sunrisers Hyderabad,toss_decision_bat,toss_decision_field
0,26-03-2022,2022,Mumbai,"Wankhede Stadium, Mumbai",Kolkata Knight Riders,131,5,133,4,Kolkata Knight Riders,complete,0,6,UT Yadav,M Nayyar,AK Chaudhary,Nitin Menon,VK Sharma,Chirra Ravikanthreddy,20,"RD Gaikwad, DP Conway, RV Uthappa, AT Rayudu, ...","AM Rahane, VR Iyer, N Rana, SS Iyer, SW Billin...",1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1
1,27-03-2022,2022,Mumbai,"Brabourne Stadium, Mumbai",Delhi Capitals,177,5,179,6,Delhi Capitals,complete,0,4,Kuldeep Yadav,Prakash Bhatt,RJ Tucker,HAS Khalid,J Madanagopal,N Pandit,20,"RG Sharma, Ishan Kishan, Anmolpreet Singh, Til...","PP Shaw, TL Seifert, Mandeep Singh, RR Pant, L...",0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1
2,27-03-2022,2022,Mumbai,"Dr DY Patil Sports Academy, Mumbai",Punjab Kings,205,2,208,5,Punjab Kings,complete,0,5,OF Smith,M Nayyar,Nitin Menon,YC Barde,AK Chaudhary,R Pandit,20,"F du Plessis, Anuj Rawat, V Kohli, KD Karthik,...","MA Agarwal, S Dhawan, PBB Rajapaksa, LS Living...",0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1
3,28-03-2022,2022,Mumbai,"Wankhede Stadium, Mumbai",Gujarat Titans,158,6,161,5,Gujarat Titans,complete,0,5,Mohammed Shami,DS Manohar,PG Pathak,VK Sharma,RJ Tucker,GR Sadashiv Iyer,20,"KL Rahul, Q de Kock, E Lewis, MK Pandey, DJ Ho...","Shubman Gill, MS Wade, V Shankar, HH Pandya, D...",0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1
4,29-03-2022,2022,Pune,"Maharashtra Cricket Association Stadium, Pune",Sunrisers Hyderabad,210,6,149,7,Rajasthan Royals,complete,61,0,SV Samson,Shakti Singh,BNJ Oxenford,UV Gandhe,KN Ananthapadmanabhan,MV Saidharshan Kumar,20,"JC Buttler, YBK Jaiswal, SV Samson, D Padikkal...","KS Williamson, Abhishek Sharma, RA Tripathi, N...",0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1

In [17]:
df_encoded.shape

(367, 46)

In [18]:
print(df_encoded.columns)

Index(['date', 'season', 'city', 'venue', 'toss_winner', 'team1_runs',
       'team1_wickets', 'team2_runs', 'team2_wickets', 'winner', 'result_type',
       'win_by_runs', 'win_by_wickets', 'player_of_match', 'match_referee',
       'umpire1', 'umpire2', 'tv_umpire', 'reserve_umpire', 'overs_limit',
       'team1_players', 'team2_players', 'team1_Chennai Super Kings',
       'team1_Delhi Capitals', 'team1_Gujarat Titans',
       'team1_Kolkata Knight Riders', 'team1_Lucknow Super Giants',
       'team1_Mumbai Indians', 'team1_Punjab Kings', 'team1_Rajasthan Royals',
       'team1_Royal Challengers Bangalore',
       'team1_Royal Challengers Bengaluru', 'team1_Sunrisers Hyderabad',
       'team2_Chennai Super Kings', 'team2_Delhi Capitals',
       'team2_Gujarat Titans', 'team2_Kolkata Knight Riders',
       'team2_Lucknow Super Giants', 'team2_Mumbai Indians',
       'team2_Punjab Kings', 'team2_Rajasthan Royals',
       'team2_Royal Challengers Bangalore',
       'team2_Royal Challengers Bengaluru', 'team2_Sunrisers Hyderabad',
       'toss_decision_bat', 'toss_decision_field'],
      dtype='object')

In [20]:
df_encoded2 = pd.get_dummies(df,columns=['team1', 'team2', 'toss_decision'],drop_first=True, dtype=int)
df_encoded2.head()

,date,season,city,venue,toss_winner,team1_runs,team1_wickets,team2_runs,team2_wickets,winner,result_type,win_by_runs,win_by_wickets,player_of_match,match_referee,umpire1,umpire2,tv_umpire,reserve_umpire,overs_limit,team1_players,team2_players,team1_Delhi Capitals,team1_Gujarat Titans,team1_Kolkata Knight Riders,team1_Lucknow Super Giants,team1_Mumbai Indians,team1_Punjab Kings,team1_Rajasthan Royals,team1_Royal Challengers Bangalore,team1_Royal Challengers Bengaluru,team1_Sunrisers Hyderabad,team2_Delhi Capitals,team2_Gujarat Titans,team2_Kolkata Knight Riders,team2_Lucknow Super Giants,team2_Mumbai Indians,team2_Punjab Kings,team2_Rajasthan Royals,team2_Royal Challengers Bangalore,team2_Royal Challengers Bengaluru,team2_Sunrisers Hyderabad,toss_decision_field
0,26-03-2022,2022,Mumbai,"Wankhede Stadium, Mumbai",Kolkata Knight Riders,131,5,133,4,Kolkata Knight Riders,complete,0,6,UT Yadav,M Nayyar,AK Chaudhary,Nitin Menon,VK Sharma,Chirra Ravikanthreddy,20,"RD Gaikwad, DP Conway, RV Uthappa, AT Rayudu, ...","AM Rahane, VR Iyer, N Rana, SS Iyer, SW Billin...",0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1
1,27-03-2022,2022,Mumbai,"Brabourne Stadium, Mumbai",Delhi Capitals,177,5,179,6,Delhi Capitals,complete,0,4,Kuldeep Yadav,Prakash Bhatt,RJ Tucker,HAS Khalid,J Madanagopal,N Pandit,20,"RG Sharma, Ishan Kishan, Anmolpreet Singh, Til...","PP Shaw, TL Seifert, Mandeep Singh, RR Pant, L...",0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1
2,27-03-2022,2022,Mumbai,"Dr DY Patil Sports Academy, Mumbai",Punjab Kings,205,2,208,5,Punjab Kings,complete,0,5,OF Smith,M Nayyar,Nitin Menon,YC Barde,AK Chaudhary,R Pandit,20,"F du Plessis, Anuj Rawat, V Kohli, KD Karthik,...","MA Agarwal, S Dhawan, PBB Rajapaksa, LS Living...",0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1
3,28-03-2022,2022,Mumbai,"Wankhede Stadium, Mumbai",Gujarat Titans,158,6,161,5,Gujarat Titans,complete,0,5,Mohammed Shami,DS Manohar,PG Pathak,VK Sharma,RJ Tucker,GR Sadashiv Iyer,20,"KL Rahul, Q de Kock, E Lewis, MK Pandey, DJ Ho...","Shubman Gill, MS Wade, V Shankar, HH Pandya, D...",0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1
4,29-03-2022,2022,Pune,"Maharashtra Cricket Association Stadium, Pune",Sunrisers Hyderabad,210,6,149,7,Rajasthan Royals,complete,61,0,SV Samson,Shakti Singh,BNJ Oxenford,UV Gandhe,KN Ananthapadmanabhan,MV Saidharshan Kumar,20,"JC Buttler, YBK Jaiswal, SV Samson, D Padikkal...","KS Williamson, Abhishek Sharma, RA Tripathi, N...",0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,1

In [22]:
print("Original Shape : ", df.shape)
print("One Hot Encoded : ",df_encoded.shape)
print("Drop Frist : ", df_encoded2.shape)

Original Shape :  (367, 25)
One Hot Encoded :  (367, 46)
Drop Frist :  (367, 43)

In [25]:
dropped_column = set(df_encoded.columns)-set(df_encoded2.columns)
print(dropped_column)

{'team1_Chennai Super Kings', 'toss_decision_bat', 'team2_Chennai Super Kings'}